### ISSUE TITLE
GUI not showing values for all devices

### ISSUE THREAD

**Issue by VinceRMP** [OpenZWave/ozw-admin#35]
It seems the GUI does not show all values for all devices. I tried it with the latest version as of today on Windows, OSX and the new allinone build which is linux based. 
I have 60+ devices added to the controller, these devices are all functioning correctly and showing up in mqtt with all the correct values. It is also possible to change them from there and Home Assistant and use them.
The values are not visible in the GUI for the first 17 devices, but the following 45 do show all the values as expected. I tried a refreshnodeinfo on the nodes that are not displaying correctly. After the refresh the node moved to the bottom of the list and shows the values, but the first 17 nodes still don't show any values. So there is a new node which did show the values and after refreshing another node it now doesn't show it anymore.

Somehow it looks like it is only possible to show values for the last 45 added nodes.
I hope the problem is clear and if not please let me know.

**Comment by Fishwaldo** [comment]
I've just added some additional logging. If you can try the allinone build 9 or 10 (not sure which build the changes will end up in) and later post the results of the config/logs/ozwadmin.log file here please?

**Comment by VinceRMP** [comment]
See the attached log file. I must say the new ozwadmin uses 100% of the cpu and hangs after a while within docker but also using osx. I tried clicking around a few nodes. So I hope you can use the information.

Edit: Above problem was on my side, don't know what happened but it seems to have settled.
I attached a new log file. Node 19 and higher show the values everything below 19 doesn't.
[ozwadmin.log](https://github.com/OpenZWave/ozw-admin/files/4732843/ozwadmin.log)

**Comment by Fishwaldo** [comment]
Can you give it another go with the allinone build-12 (should be there in a hour or so)

**Comment by VinceRMP** [comment]
I tried it again with the image openzwave/ozwdaemon:allinone-amd64-12 
It gives the same result, see attached log file:
[ozwadmin.log](https://github.com/OpenZWave/ozw-admin/files/4735418/ozwadmin.log)

**Comment by Fishwaldo** [comment]
Hi,
I added a lot more logging again - Could you try with AllInOne-13 (Builds starting soon).

**Comment by VinceRMP** [comment]
Hi, thanks for the active support!
I attached the log file (Zipped this time, logging is indeed insane :) )
[ozwadmin.log.zip](https://github.com/OpenZWave/ozw-admin/files/4737701/ozwadmin.log.zip)

**Comment by Fishwaldo** [comment]
Indeed something is very broken..... You say the MQTT Topics are all valid?

Any chance you can try a "local" copy of ozw-admin (meaning you connect to the USB device instead of over the network)

That will just help me narrow down the where the problem lies (either in the wrapper from OZW, or the "network" code to transfer the data to a remote application)

**Comment by Fishwaldo** [comment]
(I just committed back a update to turn the logging down again)

**Comment by VinceRMP** [comment]
Yeah they seem fine. All devices work as expected. In ozwadmin I can't see the current states at all or change them. This works fine from Homeassistant or the mqtt topic to change device parameters.

If you want to I can upload the ozwdaemon.log file? It shows that the values are present.

Regarding the local copy. I can do that I guess, but can I use/copy the cache file? I have quite a few battery powered devices and it takes a lot of time or effort to get them to show up without the file. Also it would be from a Windows system, but that shouldn't be a problem, right?

**Comment by Fishwaldo** [comment]
Actually - If you can wait till the Windows Client Build 128 works (should start soon) and test that version (no need to bump the ozwdaemon version)

http://bamboo.my-ho.st/bamboo/browse/OZW-OZW-WB-128/artifact

**Comment by Fishwaldo** [comment]
(via a Network Connection). If that still exhibits the problem, yes, you can copy ozwcache_*.xml from the ozwdaemon to the windows platform no problem)

**Comment by VinceRMP** [comment]
Build 126 and 127 are not good?
I can try the network client first on Windows or OSX.
For the local copy test I will probably have to wait till tomorrow before I can test it. The network will not work and that's not good in the evening..

**Comment by VinceRMP** [comment]
I just did a quick test with the local copy on the Windows system using the copied cache file.
The ozwadmin install was a few days old, but worked perfectly. It showed all the values for all devices. So perhaps it is network related. I will test the 128 build when it is finished.

**Comment by Fishwaldo** [comment]
Yeah - Build 128 is needed with a change. 

It appears to be a upstream bug - I see you have exactly 1000 "valid" values - and that relates to the cache size on the remote client. The change in 128 doesn't "warm" up the cache (so every value must be fetched as its displayed on the GUI). Hopefully that works (although it might be a bit slow).

If not, I can bump the cache size upto something like 10,000 till the upstream bug is fixed.

**Comment by VinceRMP** [comment]
Build 128 for OSX crashes when connecting to ozwdaemon.
Will try the build for Windows when it is ready.

**Comment by VinceRMP** [comment]
Windows Build 128 and the ozwadmin version included in allinone-amd64-14 also crash when connecting. So it seems the last change you did broke something else.

**Comment by ghost** [comment]
The linux allinone-amd64 image I pulled on 6/7/20 also crashes on connect.   The standalone binary also crashes on connect.

I have an older version standalone binary of ozwadmin from 5/22/20 and that used to work properly, but now it hangs on the GotValueData progress bar.

**Comment by VinceRMP** [comment]
It should work again for you when using allinone-amd64-12 or 13. With build 14 the problem started. I think it is important to downgrade completely and not only ozwadmin.

**Comment by Fishwaldo** [comment]
Sorry - Latest Builds should fix this. Can you try again

**Comment by VinceRMP** [comment]
ozwadmin does work again, but the values are still not showing it seems (using network)

**Comment by Fishwaldo** [comment]
Damn - Can you try adding this to your docker command line (for the allinone) and see if it improves things:
`-e QTRO_NODES_CACHE_SIZE=10000`

**Comment by VinceRMP** [comment]
That does work!

**Comment by Fishwaldo** [comment]
Fubar - Upstream bug I believe - https://bugreports.qt.io/browse/QTBUG-84791

I'll put in a work around once I get a reply if its a bug, or a implementation limit.

**Comment by VinceRMP** [comment]
Thank you for your help so far.
Let me know if you need further assistance with the issue.
I can keep the increased cache size active? I don't check or change values that often, so if it can cause some other issue I will remove it. As a workaround I can also use the mqtt commands directly.

**Comment by Fishwaldo** [comment]
Yeah, you can keep it - The work around I'll implement will basically do the same thing. Watch this issue for when its in place. 

My main concern is memory utilization. I will explore if we can add some "dynamic" QTRO_NODES_CACHE_SIZE environment value that is close to what the total number of ValueID's are exposed.

**Comment by Fishwaldo** [comment]
I just pushed a update that should help here. You can still set the CACHE size via a environment variable or via the Configuration Window. It should also warn you when starting if your cache size is too low

**Comment by VinceRMP** [comment]
Is that allinone build 23 or will it be the next build?
I see you are still building the ozwadmin client in Bamboo.
If it is already included in build 23, I'm not sure where to look at.
I don't see a configuration entry and no warning either?

Edit:
It will be in the next build so it seems, does the ozwdaemon also require an update?
I just check the latest ozwadmin Windows build againt allinone-23 and the configuration option is available and the warning also when starting the connection. It report that it should be increased to 2900 or higher. When I set it to 3000 the warning is gone, but the items are not yet listed.

**Comment by Fishwaldo** [comment]
If you set QTRO_NODES_CACHE_SIZE though it does work right?

**Comment by VinceRMP** [comment]
It did, but not after the last change.

**Comment by VinceRMP** [comment]
I just updated to all-in-one build-140 and now the environment setting does seem to work.
I don't know if you changed something or I made a mistake this morning when I checked it for you.

The configuration settings does not work yet though.

**Comment by Fishwaldo** [comment]
Latest Version should correct this via the Preferences Pane.

**Comment by VinceRMP** [comment]
Seems to respond as expected now. All items are visible when setting a high enough value.
Thanks!
